# Generated by Django 4.1.7 on 2023-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistrationOfSchoolsData",
            fields=[
                (
                    "time_stamp",
                    models.DateTimeField(
                        default=models.DateTimeField(auto_now_add=True)
                    ),
                ),
                (
                    "uic_number",
                    models.CharField(
                        default="0000", max_length=4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name_of_school",
                    models.CharField(default="", max_length=50, null=True),
                ),
                ("registration_number", models.IntegerField(null=True)),
                (
                    "date_of_registration",
                    models.DateField(default=models.DateField(auto_now_add=True)),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "gender_category",
                    models.CharField(
                        choices=[
                            ("boys", "boys"),
                            ("girls", "girls"),
                            ("mixed", "mixed"),
                        ],
                        default="",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "level_of_school",
                    models.CharField(
                        choices=[
                            ("ecde and primary", "ecde and primary"),
                            ("primary only", "primary only"),
                            ("junior secondary", "junior secondary"),
                            ("secondary", "secondary"),
                        ],
                        default="",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "sub_county",
                    models.CharField(
                        choices=[
                            ("kajiado east", "kajiado east"),
                            ("kajiado west", "kajiado west"),
                            ("kajiado central", "kajiado central"),
                            ("kajiado north", "kajiado north"),
                            ("kajiado south", "kajiado south"),
                            ("mashuuru", "mashuuru"),
                            ("oloililai", "oloililai"),
                        ],
                        default="",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "registration_status",
                    models.CharField(
                        choices=[
                            ("full registration", "full registration"),
                            ("provincial registration", "provincial registration"),
                            ("re-registration", "re-registration"),
                        ],
                        default="",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "accommodation_category",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("boarding", "boarding"),
                            ("day and boarding", "day and boarding"),
                        ],
                        default="",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "teacher_email",
                    models.EmailField(default="", max_length=254, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchoolsInfrastructureStatus",
            fields=[
                (
                    "uic_number",
                    models.CharField(
                        default="0000", max_length=4, primary_key=True, serialize=False
                    ),
                ),
                ("name_of_school", models.CharField(max_length=50)),
                ("date", models.DateField(default=models.DateField(auto_now_add=True))),
                ("boys_enrollment", models.IntegerField()),
                ("girls_enrollment", models.IntegerField()),
                ("total_enrollment", models.IntegerField()),
                ("number_of_permanent_classrooms", models.IntegerField()),
                ("number_of_temporary_classrooms", models.IntegerField()),
                ("number_of_boys_toilets", models.IntegerField()),
                ("number_of_girls_toilets", models.IntegerField()),
                ("number_of_staff_toilets", models.IntegerField()),
                ("number_of_taps", models.IntegerField()),
                (
                    "water_source",
                    models.CharField(
                        choices=[
                            ("river/lake", "river/lake"),
                            ("rain taped", "rain taped"),
                            ("piped/taps", "piped/taps"),
                            ("borehole/well/dam", "borehole/well/dam"),
                            ("others", "others"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "power_source",
                    models.CharField(
                        choices=[
                            ("solar", "solar"),
                            ("mains electricity", "mains electricity"),
                            ("generator", "generator"),
                            ("others", "others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("internet_connectivity", models.BooleanField(default=False)),
                (
                    "security",
                    models.CharField(
                        choices=[
                            ("fenced with gate", "fenced with gate"),
                            ("fenced with no gate", "fenced with no gate"),
                            ("no fence no gate", "no fence no gate"),
                            ("others", "others"),
                        ],
                        max_length=30,
                    ),
                ),
                ("comment", models.TextField()),
            ],
        ),
    ]
