# Generated by Django 4.1.7 on 2023-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationofschoolsdata",
            name="date_of_registration",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="registrationofschoolsdata",
            name="time_stamp",
            field=models.DateTimeField(),
        ),
    ]
