# Generated by Django 4.1.7 on 2023-05-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analysis",
            "0002_alter_registrationofschoolsdata_date_of_registration_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="schoolsinfrastructurestatus", name="date",),
        migrations.AddField(
            model_name="schoolsinfrastructurestatus",
            name="time_stamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="registrationofschoolsdata",
            name="sub_county",
            field=models.CharField(
                choices=[
                    ("isinya", "isinya"),
                    ("kajiado west", "kajiado west"),
                    ("kajiado central", "kajiado central"),
                    ("kajiado north", "kajiado north"),
                    ("loitokitok", "loitokitok"),
                    ("mashuuru", "mashuuru"),
                    ("oloililai", "oloililai"),
                ],
                default="",
                max_length=20,
                null=True,
            ),
        ),
    ]
