# Generated by Django 4.1.7 on 2023-05-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_schoolsinfrastructurestatus_teacher_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsinfrastructurestatus",
            name="other_power_sources",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="schoolsinfrastructurestatus",
            name="other_security",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="schoolsinfrastructurestatus",
            name="other_water_sources",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="schoolsinfrastructurestatus",
            name="water_source",
            field=models.CharField(max_length=100),
        ),
    ]
