# Generated by Django 4.1.7 on 2023-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolEnrollment",
            fields=[
                (
                    "uic_number",
                    models.CharField(
                        default="0000", max_length=4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sub_county",
                    models.CharField(
                        choices=[
                            ("kajiado east", "kajiado east"),
                            ("kajiado west", "kajiado west"),
                            ("kajiado central", "kajiado central"),
                            ("kajiado north", "kajiado north"),
                            ("kajiado south", "kajiado south"),
                            ("mashuuru", "mashuuru"),
                            ("Oloililai", "Oloililai"),
                        ],
                        max_length=20,
                    ),
                ),
                ("school_name", models.CharField(max_length=50)),
                ("form1_boys", models.IntegerField()),
                ("form1_girls", models.IntegerField()),
                ("form1_all", models.IntegerField()),
                ("form2_boys", models.IntegerField()),
                ("form2_girls", models.IntegerField()),
                ("form2_all", models.IntegerField()),
                ("form3_boys", models.IntegerField()),
                ("form3_girls", models.IntegerField()),
                ("form3_all", models.IntegerField()),
                ("form4_boys", models.IntegerField()),
                ("form4_girls", models.IntegerField()),
                ("form4_all", models.IntegerField()),
                ("total_boys", models.IntegerField()),
                ("total_girls", models.IntegerField()),
                ("total_all", models.IntegerField()),
            ],
        ),
    ]
